### ISSUE TITLE
Content Pipeline to prepare TIF files for training/testing

### ISSUE THREAD

**Issue by cbebry** [spectrumbranch/retro-translation-project#2]
@fmahnke is working on a content pipeline system which will help prepare game screenshots for training and testing. The background color and threshold rules will be applied in a filter in order to help input images to become used for ground truth and tests.

- [x] crop
- [x] threshold/binarization
- [x] OCR
  - [x] support both image and text output for result 

Continued in #8

**Comment by cbebry** [comment]
Adding a detector module for helping algorithmically detect crop rectangles
https://github.com/spectrumbranch/mortar/pull/9

**Comment by fmahnke** [comment]
Finished with https://github.com/spectrumbranch/mortar/pull/10
